# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'misorientationUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Misorientation(object):
    def setupUi(self, Misorientation):
        Misorientation.setObjectName(_fromUtf8("Misorientation"))
        Misorientation.resize(1200, 887)
        self.centralwidget = QtGui.QWidget(Misorientation)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_11 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.gridLayout_7 = QtGui.QGridLayout(self.settings)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.e_label = QtGui.QLabel(self.groupBox)
        self.e_label.setObjectName(_fromUtf8("e_label"))
        self.gridLayout_2.addWidget(self.e_label, 3, 0, 1, 2)
        self.hexa_button = QtGui.QCheckBox(self.groupBox)
        self.hexa_button.setObjectName(_fromUtf8("hexa_button"))
        self.gridLayout_2.addWidget(self.hexa_button, 4, 0, 1, 6)
        self.alphabetagamma_entry = QtGui.QLineEdit(self.groupBox)
        self.alphabetagamma_entry.setObjectName(_fromUtf8("alphabetagamma_entry"))
        self.gridLayout_2.addWidget(self.alphabetagamma_entry, 2, 1, 1, 5)
        self.structure_box = QtGui.QComboBox(self.groupBox)
        self.structure_box.setObjectName(_fromUtf8("structure_box"))
        self.gridLayout_2.addWidget(self.structure_box, 0, 0, 1, 6)
        self.dm_button = QtGui.QPushButton(self.groupBox)
        self.dm_button.setObjectName(_fromUtf8("dm_button"))
        self.gridLayout_2.addWidget(self.dm_button, 11, 1, 1, 1)
        self.dp_button = QtGui.QPushButton(self.groupBox)
        self.dp_button.setObjectName(_fromUtf8("dp_button"))
        self.gridLayout_2.addWidget(self.dp_button, 11, 3, 1, 1)
        self.abc_label = QtGui.QLabel(self.groupBox)
        self.abc_label.setObjectName(_fromUtf8("abc_label"))
        self.gridLayout_2.addWidget(self.abc_label, 1, 0, 1, 1)
        self.color_trace_bleu = QtGui.QRadioButton(self.groupBox)
        self.color_trace_bleu.setObjectName(_fromUtf8("color_trace_bleu"))
        self.gridLayout_2.addWidget(self.color_trace_bleu, 6, 0, 1, 1)
        self.d_label = QtGui.QLabel(self.groupBox)
        self.d_label.setObjectName(_fromUtf8("d_label"))
        self.gridLayout_2.addWidget(self.d_label, 11, 0, 1, 1)
        self.abc_entry = QtGui.QLineEdit(self.groupBox)
        self.abc_entry.setObjectName(_fromUtf8("abc_entry"))
        self.gridLayout_2.addWidget(self.abc_entry, 1, 1, 1, 5)
        self.d_label_var = QtGui.QLabel(self.groupBox)
        self.d_label_var.setText(_fromUtf8(""))
        self.d_label_var.setObjectName(_fromUtf8("d_label_var"))
        self.gridLayout_2.addWidget(self.d_label_var, 11, 4, 1, 2)
        self.color_trace_rouge = QtGui.QRadioButton(self.groupBox)
        self.color_trace_rouge.setObjectName(_fromUtf8("color_trace_rouge"))
        self.gridLayout_2.addWidget(self.color_trace_rouge, 6, 2, 1, 1)
        self.alphabetagamma_label = QtGui.QLabel(self.groupBox)
        self.alphabetagamma_label.setObjectName(_fromUtf8("alphabetagamma_label"))
        self.gridLayout_2.addWidget(self.alphabetagamma_label, 2, 0, 1, 1)
        self.d_entry = QtGui.QLineEdit(self.groupBox)
        self.d_entry.setObjectName(_fromUtf8("d_entry"))
        self.gridLayout_2.addWidget(self.d_entry, 11, 2, 1, 1)
        self.e_entry = QtGui.QLineEdit(self.groupBox)
        self.e_entry.setObjectName(_fromUtf8("e_entry"))
        self.gridLayout_2.addWidget(self.e_entry, 3, 3, 1, 3)
        self.color_trace_vert = QtGui.QRadioButton(self.groupBox)
        self.color_trace_vert.setObjectName(_fromUtf8("color_trace_vert"))
        self.gridLayout_2.addWidget(self.color_trace_vert, 6, 1, 1, 1)
        self.style_box = QtGui.QCheckBox(self.groupBox)
        self.style_box.setObjectName(_fromUtf8("style_box"))
        self.gridLayout_2.addWidget(self.style_box, 7, 0, 1, 4)
        self.gridLayout_7.addWidget(self.groupBox, 0, 2, 2, 1)
        self.crystal2_box = QtGui.QGroupBox(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crystal2_box.sizePolicy().hasHeightForWidth())
        self.crystal2_box.setSizePolicy(sizePolicy)
        self.crystal2_box.setObjectName(_fromUtf8("crystal2_box"))
        self.gridLayout_4 = QtGui.QGridLayout(self.crystal2_box)
        self.gridLayout_4.setMargin(5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.d_label_var_2 = QtGui.QLabel(self.crystal2_box)
        self.d_label_var_2.setText(_fromUtf8(""))
        self.d_label_var_2.setObjectName(_fromUtf8("d_label_var_2"))
        self.gridLayout_4.addWidget(self.d_label_var_2, 12, 5, 1, 2)
        self.dm_button_2 = QtGui.QPushButton(self.crystal2_box)
        self.dm_button_2.setObjectName(_fromUtf8("dm_button_2"))
        self.gridLayout_4.addWidget(self.dm_button_2, 12, 1, 1, 1)
        self.style_box_2 = QtGui.QCheckBox(self.crystal2_box)
        self.style_box_2.setObjectName(_fromUtf8("style_box_2"))
        self.gridLayout_4.addWidget(self.style_box_2, 8, 0, 1, 7)
        self.abc_label_2 = QtGui.QLabel(self.crystal2_box)
        self.abc_label_2.setObjectName(_fromUtf8("abc_label_2"))
        self.gridLayout_4.addWidget(self.abc_label_2, 1, 0, 1, 1)
        self.d_entry_2 = QtGui.QLineEdit(self.crystal2_box)
        self.d_entry_2.setObjectName(_fromUtf8("d_entry_2"))
        self.gridLayout_4.addWidget(self.d_entry_2, 12, 2, 1, 1)
        self.color_trace_rouge_2 = QtGui.QRadioButton(self.crystal2_box)
        self.color_trace_rouge_2.setObjectName(_fromUtf8("color_trace_rouge_2"))
        self.gridLayout_4.addWidget(self.color_trace_rouge_2, 7, 2, 1, 1)
        self.alphabetagamma_label_2 = QtGui.QLabel(self.crystal2_box)
        self.alphabetagamma_label_2.setObjectName(_fromUtf8("alphabetagamma_label_2"))
        self.gridLayout_4.addWidget(self.alphabetagamma_label_2, 3, 0, 1, 1)
        self.e_label_2 = QtGui.QLabel(self.crystal2_box)
        self.e_label_2.setObjectName(_fromUtf8("e_label_2"))
        self.gridLayout_4.addWidget(self.e_label_2, 5, 0, 1, 4)
        self.e_entry_2 = QtGui.QLineEdit(self.crystal2_box)
        self.e_entry_2.setObjectName(_fromUtf8("e_entry_2"))
        self.gridLayout_4.addWidget(self.e_entry_2, 5, 4, 1, 3)
        self.structure2_box = QtGui.QComboBox(self.crystal2_box)
        self.structure2_box.setObjectName(_fromUtf8("structure2_box"))
        self.gridLayout_4.addWidget(self.structure2_box, 0, 0, 1, 7)
        self.hexa_button_2 = QtGui.QCheckBox(self.crystal2_box)
        self.hexa_button_2.setObjectName(_fromUtf8("hexa_button_2"))
        self.gridLayout_4.addWidget(self.hexa_button_2, 6, 0, 1, 7)
        self.dp_button_2 = QtGui.QPushButton(self.crystal2_box)
        self.dp_button_2.setObjectName(_fromUtf8("dp_button_2"))
        self.gridLayout_4.addWidget(self.dp_button_2, 12, 4, 1, 1)
        self.color_trace_bleu_2 = QtGui.QRadioButton(self.crystal2_box)
        self.color_trace_bleu_2.setObjectName(_fromUtf8("color_trace_bleu_2"))
        self.gridLayout_4.addWidget(self.color_trace_bleu_2, 7, 0, 1, 1)
        self.alphabetagamma_entry_2 = QtGui.QLineEdit(self.crystal2_box)
        self.alphabetagamma_entry_2.setObjectName(_fromUtf8("alphabetagamma_entry_2"))
        self.gridLayout_4.addWidget(self.alphabetagamma_entry_2, 3, 1, 1, 6)
        self.abc_entry_2 = QtGui.QLineEdit(self.crystal2_box)
        self.abc_entry_2.setObjectName(_fromUtf8("abc_entry_2"))
        self.gridLayout_4.addWidget(self.abc_entry_2, 1, 1, 1, 6)
        self.d_label_2 = QtGui.QLabel(self.crystal2_box)
        self.d_label_2.setObjectName(_fromUtf8("d_label_2"))
        self.gridLayout_4.addWidget(self.d_label_2, 12, 0, 1, 1)
        self.color_trace_vert_2 = QtGui.QRadioButton(self.crystal2_box)
        self.color_trace_vert_2.setObjectName(_fromUtf8("color_trace_vert_2"))
        self.gridLayout_4.addWidget(self.color_trace_vert_2, 7, 1, 1, 1)
        self.gridLayout_7.addWidget(self.crystal2_box, 0, 3, 2, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.settings)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.image_angle_entry = QtGui.QLineEdit(self.groupBox_7)
        self.image_angle_entry.setObjectName(_fromUtf8("image_angle_entry"))
        self.gridLayout_12.addWidget(self.image_angle_entry, 1, 1, 1, 1)
        self.real_space_checkBox = QtGui.QCheckBox(self.groupBox_7)
        self.real_space_checkBox.setObjectName(_fromUtf8("real_space_checkBox"))
        self.gridLayout_12.addWidget(self.real_space_checkBox, 2, 0, 1, 1)
        self.image_tilt_y_label = QtGui.QLabel(self.groupBox_7)
        self.image_tilt_y_label.setObjectName(_fromUtf8("image_tilt_y_label"))
        self.gridLayout_12.addWidget(self.image_tilt_y_label, 1, 0, 1, 1)
        self.tilt_angle_entry = QtGui.QLineEdit(self.groupBox_7)
        self.tilt_angle_entry.setObjectName(_fromUtf8("tilt_angle_entry"))
        self.gridLayout_12.addWidget(self.tilt_angle_entry, 0, 1, 1, 1)
        self.tilt_angle_label = QtGui.QLabel(self.groupBox_7)
        self.tilt_angle_label.setObjectName(_fromUtf8("tilt_angle_label"))
        self.gridLayout_12.addWidget(self.tilt_angle_label, 0, 0, 1, 1)
        self.uvw_button = QtGui.QCheckBox(self.groupBox_7)
        self.uvw_button.setObjectName(_fromUtf8("uvw_button"))
        self.gridLayout_12.addWidget(self.uvw_button, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_7, 0, 0, 1, 2)
        self.groupBox_10 = QtGui.QGroupBox(self.settings)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.text_size_entry = QtGui.QLineEdit(self.groupBox_10)
        self.text_size_entry.setObjectName(_fromUtf8("text_size_entry"))
        self.gridLayout_3.addWidget(self.text_size_entry, 3, 1, 1, 1)
        self.wulff_button = QtGui.QCheckBox(self.groupBox_10)
        self.wulff_button.setObjectName(_fromUtf8("wulff_button"))
        self.gridLayout_3.addWidget(self.wulff_button, 0, 0, 1, 2)
        self.text_size_label = QtGui.QLabel(self.groupBox_10)
        self.text_size_label.setObjectName(_fromUtf8("text_size_label"))
        self.gridLayout_3.addWidget(self.text_size_label, 3, 0, 1, 1)
        self.size_var = QtGui.QLineEdit(self.groupBox_10)
        self.size_var.setObjectName(_fromUtf8("size_var"))
        self.gridLayout_3.addWidget(self.size_var, 2, 1, 1, 1)
        self.reset_view_button = QtGui.QPushButton(self.groupBox_10)
        self.reset_view_button.setObjectName(_fromUtf8("reset_view_button"))
        self.gridLayout_3.addWidget(self.reset_view_button, 4, 0, 1, 2)
        self.size_var_label = QtGui.QLabel(self.groupBox_10)
        self.size_var_label.setObjectName(_fromUtf8("size_var_label"))
        self.gridLayout_3.addWidget(self.size_var_label, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lab_coord = QtGui.QLabel(self.groupBox_5)
        self.lab_coord.setObjectName(_fromUtf8("lab_coord"))
        self.gridLayout_6.addWidget(self.lab_coord, 6, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 3, 0, 1, 1)
        self.angle_euler_label = QtGui.QLabel(self.groupBox_5)
        self.angle_euler_label.setText(_fromUtf8(""))
        self.angle_euler_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.angle_euler_label.setObjectName(_fromUtf8("angle_euler_label"))
        self.gridLayout_6.addWidget(self.angle_euler_label, 1, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.angle_euler_label_2 = QtGui.QLabel(self.groupBox_5)
        self.angle_euler_label_2.setText(_fromUtf8(""))
        self.angle_euler_label_2.setObjectName(_fromUtf8("angle_euler_label_2"))
        self.gridLayout_6.addWidget(self.angle_euler_label_2, 4, 1, 1, 2)
        self.phi1phiphi2_entry = QtGui.QLineEdit(self.groupBox_5)
        self.phi1phiphi2_entry.setObjectName(_fromUtf8("phi1phiphi2_entry"))
        self.gridLayout_6.addWidget(self.phi1phiphi2_entry, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 4, 0, 1, 1)
        self.button_trace2 = QtGui.QPushButton(self.groupBox_5)
        self.button_trace2.setObjectName(_fromUtf8("button_trace2"))
        self.gridLayout_6.addWidget(self.button_trace2, 5, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 7, 1, 1, 4)
        self.coord_label = QtGui.QLabel(self.groupBox_5)
        self.coord_label.setText(_fromUtf8(""))
        self.coord_label.setObjectName(_fromUtf8("coord_label"))
        self.gridLayout_6.addWidget(self.coord_label, 6, 1, 1, 1)
        self.phi1phiphi2_2_entry = QtGui.QLineEdit(self.groupBox_5)
        self.phi1phiphi2_2_entry.setObjectName(_fromUtf8("phi1phiphi2_2_entry"))
        self.gridLayout_6.addWidget(self.phi1phiphi2_2_entry, 3, 1, 1, 2)
        self.lab_euler2 = QtGui.QLabel(self.groupBox_5)
        self.lab_euler2.setObjectName(_fromUtf8("lab_euler2"))
        self.gridLayout_6.addWidget(self.lab_euler2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 3, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pole_entry = QtGui.QLineEdit(self.groupBox_4)
        self.pole_entry.setObjectName(_fromUtf8("pole_entry"))
        self.gridLayout_5.addWidget(self.pole_entry, 0, 0, 1, 3)
        self.undo_trace_plan_sym_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_trace_plan_sym_button.setObjectName(_fromUtf8("undo_trace_plan_sym_button"))
        self.gridLayout_5.addWidget(self.undo_trace_plan_sym_button, 4, 2, 1, 1)
        self.trace_plan_sym_button = QtGui.QPushButton(self.groupBox_4)
        self.trace_plan_sym_button.setObjectName(_fromUtf8("trace_plan_sym_button"))
        self.gridLayout_5.addWidget(self.trace_plan_sym_button, 4, 0, 1, 2)
        self.addpole_button = QtGui.QPushButton(self.groupBox_4)
        self.addpole_button.setObjectName(_fromUtf8("addpole_button"))
        self.gridLayout_5.addWidget(self.addpole_button, 1, 0, 1, 2)
        self.undo_addpole_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_addpole_button.setObjectName(_fromUtf8("undo_addpole_button"))
        self.gridLayout_5.addWidget(self.undo_addpole_button, 1, 2, 1, 1)
        self.undo_sym_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_sym_button.setObjectName(_fromUtf8("undo_sym_button"))
        self.gridLayout_5.addWidget(self.undo_sym_button, 2, 2, 1, 1)
        self.sym_button = QtGui.QPushButton(self.groupBox_4)
        self.sym_button.setObjectName(_fromUtf8("sym_button"))
        self.gridLayout_5.addWidget(self.sym_button, 2, 0, 1, 2)
        self.trace_plan_button = QtGui.QPushButton(self.groupBox_4)
        self.trace_plan_button.setObjectName(_fromUtf8("trace_plan_button"))
        self.gridLayout_5.addWidget(self.trace_plan_button, 3, 0, 1, 2)
        self.undo_trace_plan_button = QtGui.QPushButton(self.groupBox_4)
        self.undo_trace_plan_button.setObjectName(_fromUtf8("undo_trace_plan_button"))
        self.gridLayout_5.addWidget(self.undo_trace_plan_button, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.crystal1_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.crystal1_radioButton.setObjectName(_fromUtf8("crystal1_radioButton"))
        self.gridLayout_8.addWidget(self.crystal1_radioButton, 0, 0, 1, 1)
        self.crystal2_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.crystal2_radioButton.setObjectName(_fromUtf8("crystal2_radioButton"))
        self.gridLayout_8.addWidget(self.crystal2_radioButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.angle_alpha_label_2 = QtGui.QLabel(self.groupBox_3)
        self.angle_alpha_label_2.setText(_fromUtf8(""))
        self.angle_alpha_label_2.setObjectName(_fromUtf8("angle_alpha_label_2"))
        self.gridLayout_9.addWidget(self.angle_alpha_label_2, 2, 3, 1, 1)
        self.angle_beta_label_2 = QtGui.QLabel(self.groupBox_3)
        self.angle_beta_label_2.setText(_fromUtf8(""))
        self.angle_beta_label_2.setObjectName(_fromUtf8("angle_beta_label_2"))
        self.gridLayout_9.addWidget(self.angle_beta_label_2, 4, 3, 1, 1)
        self.angle_z_label_2 = QtGui.QLabel(self.groupBox_3)
        self.angle_z_label_2.setText(_fromUtf8(""))
        self.angle_z_label_2.setObjectName(_fromUtf8("angle_z_label_2"))
        self.gridLayout_9.addWidget(self.angle_z_label_2, 6, 3, 1, 1)
        self.angle_z_buttonp = QtGui.QPushButton(self.groupBox_3)
        self.angle_z_buttonp.setObjectName(_fromUtf8("angle_z_buttonp"))
        self.gridLayout_9.addWidget(self.angle_z_buttonp, 6, 2, 1, 1)
        self.angle_alpha_buttonm = QtGui.QPushButton(self.groupBox_3)
        self.angle_alpha_buttonm.setObjectName(_fromUtf8("angle_alpha_buttonm"))
        self.gridLayout_9.addWidget(self.angle_alpha_buttonm, 2, 0, 1, 1)
        self.angle_alpha_label = QtGui.QLabel(self.groupBox_3)
        self.angle_alpha_label.setObjectName(_fromUtf8("angle_alpha_label"))
        self.gridLayout_9.addWidget(self.angle_alpha_label, 1, 0, 1, 2)
        self.lock_checkButton = QtGui.QCheckBox(self.groupBox_3)
        self.lock_checkButton.setObjectName(_fromUtf8("lock_checkButton"))
        self.gridLayout_9.addWidget(self.lock_checkButton, 0, 0, 1, 3)
        self.angle_z_label = QtGui.QLabel(self.groupBox_3)
        self.angle_z_label.setObjectName(_fromUtf8("angle_z_label"))
        self.gridLayout_9.addWidget(self.angle_z_label, 5, 0, 1, 2)
        self.angle_z_entry = QtGui.QLineEdit(self.groupBox_3)
        self.angle_z_entry.setObjectName(_fromUtf8("angle_z_entry"))
        self.gridLayout_9.addWidget(self.angle_z_entry, 6, 1, 1, 1)
        self.angle_z_buttonm = QtGui.QPushButton(self.groupBox_3)
        self.angle_z_buttonm.setObjectName(_fromUtf8("angle_z_buttonm"))
        self.gridLayout_9.addWidget(self.angle_z_buttonm, 6, 0, 1, 1)
        self.theta_signBox = QtGui.QCheckBox(self.groupBox_3)
        self.theta_signBox.setText(_fromUtf8(""))
        self.theta_signBox.setObjectName(_fromUtf8("theta_signBox"))
        self.gridLayout_9.addWidget(self.theta_signBox, 5, 2, 1, 1)
        self.angle_beta_buttonp = QtGui.QPushButton(self.groupBox_3)
        self.angle_beta_buttonp.setObjectName(_fromUtf8("angle_beta_buttonp"))
        self.gridLayout_9.addWidget(self.angle_beta_buttonp, 4, 2, 1, 1)
        self.angle_beta_entry = QtGui.QLineEdit(self.groupBox_3)
        self.angle_beta_entry.setObjectName(_fromUtf8("angle_beta_entry"))
        self.gridLayout_9.addWidget(self.angle_beta_entry, 4, 1, 1, 1)
        self.angle_beta_buttonm = QtGui.QPushButton(self.groupBox_3)
        self.angle_beta_buttonm.setObjectName(_fromUtf8("angle_beta_buttonm"))
        self.gridLayout_9.addWidget(self.angle_beta_buttonm, 4, 0, 1, 1)
        self.beta_signBox = QtGui.QCheckBox(self.groupBox_3)
        self.beta_signBox.setText(_fromUtf8(""))
        self.beta_signBox.setObjectName(_fromUtf8("beta_signBox"))
        self.gridLayout_9.addWidget(self.beta_signBox, 3, 2, 1, 1)
        self.alpha_signBox = QtGui.QCheckBox(self.groupBox_3)
        self.alpha_signBox.setText(_fromUtf8(""))
        self.alpha_signBox.setObjectName(_fromUtf8("alpha_signBox"))
        self.gridLayout_9.addWidget(self.alpha_signBox, 1, 2, 1, 1)
        self.angle_alpha_buttonp = QtGui.QPushButton(self.groupBox_3)
        self.angle_alpha_buttonp.setObjectName(_fromUtf8("angle_alpha_buttonp"))
        self.gridLayout_9.addWidget(self.angle_alpha_buttonp, 2, 2, 1, 1)
        self.angle_alpha_entry = QtGui.QLineEdit(self.groupBox_3)
        self.angle_alpha_entry.setObjectName(_fromUtf8("angle_alpha_entry"))
        self.gridLayout_9.addWidget(self.angle_alpha_entry, 2, 1, 1, 1)
        self.angle_beta_label = QtGui.QLabel(self.groupBox_3)
        self.angle_beta_label.setObjectName(_fromUtf8("angle_beta_label"))
        self.gridLayout_9.addWidget(self.angle_beta_label, 3, 0, 1, 2)
        self.rot_gp_button = QtGui.QPushButton(self.groupBox_3)
        self.rot_gp_button.setObjectName(_fromUtf8("rot_gp_button"))
        self.gridLayout_9.addWidget(self.rot_gp_button, 8, 2, 1, 1)
        self.rot_g_entry = QtGui.QLineEdit(self.groupBox_3)
        self.rot_g_entry.setObjectName(_fromUtf8("rot_g_entry"))
        self.gridLayout_9.addWidget(self.rot_g_entry, 8, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 7, 0, 1, 1)
        self.rot_gm_button = QtGui.QPushButton(self.groupBox_3)
        self.rot_gm_button.setObjectName(_fromUtf8("rot_gm_button"))
        self.gridLayout_9.addWidget(self.rot_gm_button, 8, 0, 1, 1)
        self.rg_label = QtGui.QLabel(self.groupBox_3)
        self.rg_label.setText(_fromUtf8(""))
        self.rg_label.setObjectName(_fromUtf8("rg_label"))
        self.gridLayout_9.addWidget(self.rg_label, 8, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.mplvl = QtGui.QGridLayout()
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.gridLayout_10.addLayout(self.mplvl, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.misorientation = QtGui.QWidget()
        self.misorientation.setObjectName(_fromUtf8("misorientation"))
        self.gridLayout_13 = QtGui.QGridLayout(self.misorientation)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.misorientation_button = QtGui.QPushButton(self.misorientation)
        self.misorientation_button.setObjectName(_fromUtf8("misorientation_button"))
        self.gridLayout_13.addWidget(self.misorientation_button, 0, 0, 1, 1)
        self.numbers_checkBox = QtGui.QCheckBox(self.misorientation)
        self.numbers_checkBox.setObjectName(_fromUtf8("numbers_checkBox"))
        self.gridLayout_13.addWidget(self.numbers_checkBox, 2, 0, 1, 1)
        self.axis_checkBox = QtGui.QCheckBox(self.misorientation)
        self.axis_checkBox.setObjectName(_fromUtf8("axis_checkBox"))
        self.gridLayout_13.addWidget(self.axis_checkBox, 3, 0, 1, 1)
        self.clear_misorientation_button = QtGui.QPushButton(self.misorientation)
        self.clear_misorientation_button.setObjectName(_fromUtf8("clear_misorientation_button"))
        self.gridLayout_13.addWidget(self.clear_misorientation_button, 1, 0, 1, 1)
        self.misorientation_list = QtGui.QTableWidget(self.misorientation)
        self.misorientation_list.setObjectName(_fromUtf8("misorientation_list"))
        self.misorientation_list.setColumnCount(0)
        self.misorientation_list.setRowCount(0)
        self.gridLayout_13.addWidget(self.misorientation_list, 4, 0, 1, 1)
        self.tabWidget.addTab(self.misorientation, _fromUtf8(""))
        self.gridLayout_11.addWidget(self.tabWidget, 0, 0, 1, 1)
        Misorientation.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Misorientation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        Misorientation.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Misorientation)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Misorientation.setStatusBar(self.statusbar)
        self.actionSave_figure = QtGui.QAction(Misorientation)
        self.actionSave_figure.setObjectName(_fromUtf8("actionSave_figure"))
        self.actionCalculate_Schmid_factor = QtGui.QAction(Misorientation)
        self.actionCalculate_Schmid_factor.setObjectName(_fromUtf8("actionCalculate_Schmid_factor"))
        self.actionCalculate_angle = QtGui.QAction(Misorientation)
        self.actionCalculate_angle.setObjectName(_fromUtf8("actionCalculate_angle"))
        self.actionCalculate_xyz = QtGui.QAction(Misorientation)
        self.actionCalculate_xyz.setObjectName(_fromUtf8("actionCalculate_xyz"))
        self.actionCalculate_apparent_width = QtGui.QAction(Misorientation)
        self.actionCalculate_apparent_width.setObjectName(_fromUtf8("actionCalculate_apparent_width"))
        self.actionPlanes = QtGui.QAction(Misorientation)
        self.actionPlanes.setObjectName(_fromUtf8("actionPlanes"))
        self.actionProj_directions = QtGui.QAction(Misorientation)
        self.actionProj_directions.setObjectName(_fromUtf8("actionProj_directions"))
        self.actionPlane_cone = QtGui.QAction(Misorientation)
        self.actionPlane_cone.setObjectName(_fromUtf8("actionPlane_cone"))
        self.actionCalculate_intersections = QtGui.QAction(Misorientation)
        self.actionCalculate_intersections.setObjectName(_fromUtf8("actionCalculate_intersections"))
        self.actionHkl_uvw = QtGui.QAction(Misorientation)
        self.actionHkl_uvw.setObjectName(_fromUtf8("actionHkl_uvw"))
        self.actionPlot_Kikuchi_lines = QtGui.QAction(Misorientation)
        self.actionPlot_Kikuchi_lines.setObjectName(_fromUtf8("actionPlot_Kikuchi_lines"))
        self.menuSave.addAction(self.actionSave_figure)
        self.menubar.addAction(self.menuSave.menuAction())

        self.retranslateUi(Misorientation)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Misorientation)
        Misorientation.setTabOrder(self.tabWidget, self.tilt_angle_entry)
        Misorientation.setTabOrder(self.tilt_angle_entry, self.image_angle_entry)
        Misorientation.setTabOrder(self.image_angle_entry, self.real_space_checkBox)
        Misorientation.setTabOrder(self.real_space_checkBox, self.uvw_button)
        Misorientation.setTabOrder(self.uvw_button, self.wulff_button)
        Misorientation.setTabOrder(self.wulff_button, self.size_var)
        Misorientation.setTabOrder(self.size_var, self.text_size_entry)
        Misorientation.setTabOrder(self.text_size_entry, self.reset_view_button)
        Misorientation.setTabOrder(self.reset_view_button, self.structure_box)
        Misorientation.setTabOrder(self.structure_box, self.abc_entry)
        Misorientation.setTabOrder(self.abc_entry, self.alphabetagamma_entry)
        Misorientation.setTabOrder(self.alphabetagamma_entry, self.e_entry)
        Misorientation.setTabOrder(self.e_entry, self.hexa_button)
        Misorientation.setTabOrder(self.hexa_button, self.color_trace_bleu)
        Misorientation.setTabOrder(self.color_trace_bleu, self.color_trace_vert)
        Misorientation.setTabOrder(self.color_trace_vert, self.color_trace_rouge)
        Misorientation.setTabOrder(self.color_trace_rouge, self.style_box)
        Misorientation.setTabOrder(self.style_box, self.dm_button)
        Misorientation.setTabOrder(self.dm_button, self.d_entry)
        Misorientation.setTabOrder(self.d_entry, self.dp_button)
        Misorientation.setTabOrder(self.dp_button, self.structure2_box)
        Misorientation.setTabOrder(self.structure2_box, self.abc_entry_2)
        Misorientation.setTabOrder(self.abc_entry_2, self.alphabetagamma_entry_2)
        Misorientation.setTabOrder(self.alphabetagamma_entry_2, self.e_entry_2)
        Misorientation.setTabOrder(self.e_entry_2, self.hexa_button_2)
        Misorientation.setTabOrder(self.hexa_button_2, self.color_trace_bleu_2)
        Misorientation.setTabOrder(self.color_trace_bleu_2, self.color_trace_vert_2)
        Misorientation.setTabOrder(self.color_trace_vert_2, self.color_trace_rouge_2)
        Misorientation.setTabOrder(self.color_trace_rouge_2, self.style_box_2)
        Misorientation.setTabOrder(self.style_box_2, self.dm_button_2)
        Misorientation.setTabOrder(self.dm_button_2, self.d_entry_2)
        Misorientation.setTabOrder(self.d_entry_2, self.dp_button_2)
        Misorientation.setTabOrder(self.dp_button_2, self.crystal1_radioButton)
        Misorientation.setTabOrder(self.crystal1_radioButton, self.crystal2_radioButton)
        Misorientation.setTabOrder(self.crystal2_radioButton, self.lock_checkButton)
        Misorientation.setTabOrder(self.lock_checkButton, self.angle_alpha_buttonm)
        Misorientation.setTabOrder(self.angle_alpha_buttonm, self.angle_alpha_entry)
        Misorientation.setTabOrder(self.angle_alpha_entry, self.alpha_signBox)
        Misorientation.setTabOrder(self.alpha_signBox, self.angle_alpha_buttonp)
        Misorientation.setTabOrder(self.angle_alpha_buttonp, self.angle_beta_buttonm)
        Misorientation.setTabOrder(self.angle_beta_buttonm, self.angle_beta_entry)
        Misorientation.setTabOrder(self.angle_beta_entry, self.beta_signBox)
        Misorientation.setTabOrder(self.beta_signBox, self.angle_beta_buttonp)
        Misorientation.setTabOrder(self.angle_beta_buttonp, self.angle_z_buttonm)
        Misorientation.setTabOrder(self.angle_z_buttonm, self.angle_z_entry)
        Misorientation.setTabOrder(self.angle_z_entry, self.theta_signBox)
        Misorientation.setTabOrder(self.theta_signBox, self.angle_z_buttonp)
        Misorientation.setTabOrder(self.angle_z_buttonp, self.rot_gm_button)
        Misorientation.setTabOrder(self.rot_gm_button, self.rot_g_entry)
        Misorientation.setTabOrder(self.rot_g_entry, self.rot_gp_button)
        Misorientation.setTabOrder(self.rot_gp_button, self.pole_entry)
        Misorientation.setTabOrder(self.pole_entry, self.addpole_button)
        Misorientation.setTabOrder(self.addpole_button, self.undo_addpole_button)
        Misorientation.setTabOrder(self.undo_addpole_button, self.sym_button)
        Misorientation.setTabOrder(self.sym_button, self.undo_sym_button)
        Misorientation.setTabOrder(self.undo_sym_button, self.trace_plan_button)
        Misorientation.setTabOrder(self.trace_plan_button, self.undo_trace_plan_button)
        Misorientation.setTabOrder(self.undo_trace_plan_button, self.trace_plan_sym_button)
        Misorientation.setTabOrder(self.trace_plan_sym_button, self.undo_trace_plan_sym_button)
        Misorientation.setTabOrder(self.undo_trace_plan_sym_button, self.phi1phiphi2_entry)
        Misorientation.setTabOrder(self.phi1phiphi2_entry, self.phi1phiphi2_2_entry)
        Misorientation.setTabOrder(self.phi1phiphi2_2_entry, self.button_trace2)
        Misorientation.setTabOrder(self.button_trace2, self.misorientation_button)
        Misorientation.setTabOrder(self.misorientation_button, self.clear_misorientation_button)
        Misorientation.setTabOrder(self.clear_misorientation_button, self.numbers_checkBox)
        Misorientation.setTabOrder(self.numbers_checkBox, self.axis_checkBox)
        Misorientation.setTabOrder(self.axis_checkBox, self.misorientation_list)

    def retranslateUi(self, Misorientation):
        Misorientation.setWindowTitle(_translate("Misorientation", "Misorientation", None))
        self.groupBox.setTitle(_translate("Misorientation", "Crystal 1", None))
        self.e_label.setText(_translate("Misorientation", "max indices", None))
        self.hexa_button.setText(_translate("Misorientation", "hexa", None))
        self.dm_button.setText(_translate("Misorientation", "-", None))
        self.dp_button.setText(_translate("Misorientation", "+", None))
        self.abc_label.setText(_translate("Misorientation", "a,b,c", None))
        self.color_trace_bleu.setText(_translate("Misorientation", "blue", None))
        self.d_label.setText(_translate("Misorientation", "d", None))
        self.color_trace_rouge.setText(_translate("Misorientation", "red", None))
        self.alphabetagamma_label.setText(_translate("Misorientation", "<p>&alpha;, &beta;, &gamma;</p>", None))
        self.color_trace_vert.setText(_translate("Misorientation", "green", None))
        self.style_box.setText(_translate("Misorientation", "open/filled", None))
        self.crystal2_box.setTitle(_translate("Misorientation", "Crystal 2", None))
        self.dm_button_2.setText(_translate("Misorientation", "-", None))
        self.style_box_2.setText(_translate("Misorientation", "open/filled", None))
        self.abc_label_2.setText(_translate("Misorientation", "a,b,c", None))
        self.color_trace_rouge_2.setText(_translate("Misorientation", "red", None))
        self.alphabetagamma_label_2.setText(_translate("Misorientation", "<p>&alpha;, &beta;, &gamma;</p>", None))
        self.e_label_2.setText(_translate("Misorientation", "max indices", None))
        self.hexa_button_2.setText(_translate("Misorientation", "hexa", None))
        self.dp_button_2.setText(_translate("Misorientation", "+", None))
        self.color_trace_bleu_2.setText(_translate("Misorientation", "blue", None))
        self.d_label_2.setText(_translate("Misorientation", "d", None))
        self.color_trace_vert_2.setText(_translate("Misorientation", "green", None))
        self.groupBox_7.setTitle(_translate("Misorientation", "Settings", None))
        self.real_space_checkBox.setText(_translate("Misorientation", "work in real space", None))
        self.image_tilt_y_label.setText(_translate("Misorientation", "Image α-tilt/y angle", None))
        self.tilt_angle_label.setText(_translate("Misorientation", "Diffraction α-tilt/y angle", None))
        self.uvw_button.setText(_translate("Misorientation", "uvw", None))
        self.groupBox_10.setTitle(_translate("Misorientation", "Layout", None))
        self.wulff_button.setText(_translate("Misorientation", "Wulff net", None))
        self.text_size_label.setText(_translate("Misorientation", "Text size", None))
        self.reset_view_button.setText(_translate("Misorientation", "Update/Reset view", None))
        self.size_var_label.setText(_translate("Misorientation", "Marker size", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("Misorientation", "settings", None))
        self.groupBox_5.setTitle(_translate("Misorientation", "Euler Angles", None))
        self.lab_coord.setText(_translate("Misorientation", "Tilt, Inclin.", None))
        self.label_2.setText(_translate("Misorientation", "Crystal 2", None))
        self.label.setText(_translate("Misorientation", "Crystal 1", None))
        self.label_3.setText(_translate("Misorientation", "φ 1 , Φ , φ2", None))
        self.button_trace2.setText(_translate("Misorientation", "PLOT", None))
        self.lab_euler2.setText(_translate("Misorientation", "<html><head/><body><p>φ<span style=\" vertical-align:sub;\"> 1</span> , Φ , φ<span style=\" vertical-align:sub;\">2</span></p></body></html>", None))
        self.groupBox_4.setTitle(_translate("Misorientation", "Pole/Direction", None))
        self.undo_trace_plan_sym_button.setText(_translate("Misorientation", "-", None))
        self.trace_plan_sym_button.setText(_translate("Misorientation", "Sym Plane", None))
        self.addpole_button.setText(_translate("Misorientation", "Add", None))
        self.undo_addpole_button.setText(_translate("Misorientation", "-", None))
        self.undo_sym_button.setText(_translate("Misorientation", "-", None))
        self.sym_button.setText(_translate("Misorientation", "Symmetry", None))
        self.trace_plan_button.setText(_translate("Misorientation", " Plane", None))
        self.undo_trace_plan_button.setText(_translate("Misorientation", "-", None))
        self.groupBox_2.setTitle(_translate("Misorientation", "Switch", None))
        self.crystal1_radioButton.setText(_translate("Misorientation", "crystal 1", None))
        self.crystal2_radioButton.setText(_translate("Misorientation", "crystal 2", None))
        self.groupBox_3.setTitle(_translate("Misorientation", "Rotation", None))
        self.angle_z_buttonp.setText(_translate("Misorientation", "+", None))
        self.angle_alpha_buttonm.setText(_translate("Misorientation", "-", None))
        self.angle_alpha_label.setText(_translate("Misorientation", "<html><head/><body><p>α (AC)</p></body></html>", None))
        self.lock_checkButton.setText(_translate("Misorientation", "Lock Axes", None))
        self.angle_z_label.setText(_translate("Misorientation", "<html><head/><body><p>θ (AC)</p></body></html>", None))
        self.angle_z_buttonm.setText(_translate("Misorientation", "-", None))
        self.angle_beta_buttonp.setText(_translate("Misorientation", "+", None))
        self.angle_beta_buttonm.setText(_translate("Misorientation", "-", None))
        self.angle_alpha_buttonp.setText(_translate("Misorientation", "+", None))
        self.angle_beta_label.setText(_translate("Misorientation", "<html><head/><body><p>β (AC)</p></body></html>", None))
        self.rot_gp_button.setText(_translate("Misorientation", "+", None))
        self.label_4.setText(_translate("Misorientation", "g", None))
        self.rot_gm_button.setText(_translate("Misorientation", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Misorientation", "stereo-proj", None))
        self.misorientation_button.setText(_translate("Misorientation", "Find misorientation & Plot Angle/Axes", None))
        self.numbers_checkBox.setText(_translate("Misorientation", "show numbers", None))
        self.axis_checkBox.setText(_translate("Misorientation", "show axes", None))
        self.clear_misorientation_button.setText(_translate("Misorientation", "Clear plot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.misorientation), _translate("Misorientation", "misorientation", None))
        self.menuSave.setTitle(_translate("Misorientation", "Save", None))
        self.actionSave_figure.setText(_translate("Misorientation", "Save figure", None))
        self.actionCalculate_Schmid_factor.setText(_translate("Misorientation", "calculate Schmid factor", None))
        self.actionCalculate_angle.setText(_translate("Misorientation", "Calculate angle", None))
        self.actionCalculate_xyz.setText(_translate("Misorientation", "calculate xyz directions", None))
        self.actionCalculate_apparent_width.setText(_translate("Misorientation", "Calculate apparent width", None))
        self.actionPlanes.setText(_translate("Misorientation", "planes", None))
        self.actionProj_directions.setText(_translate("Misorientation", "proj. directions", None))
        self.actionPlane_cone.setText(_translate("Misorientation", "plane-cone", None))
        self.actionCalculate_intersections.setText(_translate("Misorientation", "Calculate intersections", None))
        self.actionHkl_uvw.setText(_translate("Misorientation", "hkl <> uvw", None))
        self.actionPlot_Kikuchi_lines.setText(_translate("Misorientation", "plot Kikuchi lines or diffraction pattern", None))

