# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kikuchiUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Kikuchi(object):
    def setupUi(self, Kikuchi):
        Kikuchi.setObjectName(_fromUtf8("Kikuchi"))
        Kikuchi.resize(1213, 783)
        self.centralwidget = QtGui.QWidget(Kikuchi)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.Button_addband = QtGui.QPushButton(self.groupBox_9)
        self.Button_addband.setEnabled(True)
        self.Button_addband.setObjectName(_fromUtf8("Button_addband"))
        self.gridLayout_10.addWidget(self.Button_addband, 2, 3, 1, 1)
        self.ListBox_d_2 = QtGui.QListWidget(self.groupBox_9)
        self.ListBox_d_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListBox_d_2.sizePolicy().hasHeightForWidth())
        self.ListBox_d_2.setSizePolicy(sizePolicy)
        self.ListBox_d_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ListBox_d_2.setObjectName(_fromUtf8("ListBox_d_2"))
        self.gridLayout_10.addWidget(self.ListBox_d_2, 2, 0, 2, 3)
        self.Button_run = QtGui.QPushButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Button_run.setFont(font)
        self.Button_run.setObjectName(_fromUtf8("Button_run"))
        self.gridLayout_10.addWidget(self.Button_run, 10, 0, 2, 4)
        self.Button_remove_band = QtGui.QPushButton(self.groupBox_9)
        self.Button_remove_band.setObjectName(_fromUtf8("Button_remove_band"))
        self.gridLayout_10.addWidget(self.Button_remove_band, 3, 3, 1, 1)
        self.tol_entry = QtGui.QLineEdit(self.groupBox_9)
        self.tol_entry.setObjectName(_fromUtf8("tol_entry"))
        self.gridLayout_10.addWidget(self.tol_entry, 4, 2, 1, 1)
        self.ListBox_theo = QtGui.QListWidget(self.groupBox_9)
        self.ListBox_theo.setObjectName(_fromUtf8("ListBox_theo"))
        self.gridLayout_10.addWidget(self.ListBox_theo, 13, 0, 2, 4)
        self.plot_bands_button = QtGui.QPushButton(self.groupBox_9)
        self.plot_bands_button.setObjectName(_fromUtf8("plot_bands_button"))
        self.gridLayout_10.addWidget(self.plot_bands_button, 4, 3, 1, 1)
        self.Button_orientation = QtGui.QPushButton(self.groupBox_9)
        self.Button_orientation.setObjectName(_fromUtf8("Button_orientation"))
        self.gridLayout_10.addWidget(self.Button_orientation, 15, 0, 1, 4)
        self.Button_add_center = QtGui.QPushButton(self.groupBox_9)
        self.Button_add_center.setObjectName(_fromUtf8("Button_add_center"))
        self.gridLayout_10.addWidget(self.Button_add_center, 0, 0, 1, 2)
        self.centerLine = QtGui.QLineEdit(self.groupBox_9)
        self.centerLine.setObjectName(_fromUtf8("centerLine"))
        self.gridLayout_10.addWidget(self.centerLine, 0, 2, 1, 2)
        self.label = QtGui.QLabel(self.groupBox_9)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 4, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_9, 1, 0, 2, 5)
        self.groupBox = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.a_label = QtGui.QLabel(self.groupBox)
        self.a_label.setObjectName(_fromUtf8("a_label"))
        self.gridLayout_2.addWidget(self.a_label, 0, 0, 1, 1)
        self.abc_entry = QtGui.QLineEdit(self.groupBox)
        self.abc_entry.setObjectName(_fromUtf8("abc_entry"))
        self.gridLayout_2.addWidget(self.abc_entry, 0, 2, 1, 1)
        self.d_label_var = QtGui.QLabel(self.groupBox)
        self.d_label_var.setText(_fromUtf8(""))
        self.d_label_var.setObjectName(_fromUtf8("d_label_var"))
        self.gridLayout_2.addWidget(self.d_label_var, 9, 5, 1, 1)
        self.alpha_label = QtGui.QLabel(self.groupBox)
        self.alpha_label.setObjectName(_fromUtf8("alpha_label"))
        self.gridLayout_2.addWidget(self.alpha_label, 9, 0, 1, 1)
        self.indice_label = QtGui.QLabel(self.groupBox)
        self.indice_label.setObjectName(_fromUtf8("indice_label"))
        self.gridLayout_2.addWidget(self.indice_label, 14, 0, 1, 1)
        self.space_group_label = QtGui.QLabel(self.groupBox)
        self.space_group_label.setObjectName(_fromUtf8("space_group_label"))
        self.gridLayout_2.addWidget(self.space_group_label, 15, 0, 1, 1)
        self.brightness_label = QtGui.QLabel(self.groupBox)
        self.brightness_label.setObjectName(_fromUtf8("brightness_label"))
        self.gridLayout_2.addWidget(self.brightness_label, 16, 0, 1, 1)
        self.alphabetagamma_entry = QtGui.QLineEdit(self.groupBox)
        self.alphabetagamma_entry.setObjectName(_fromUtf8("alphabetagamma_entry"))
        self.gridLayout_2.addWidget(self.alphabetagamma_entry, 9, 2, 1, 1)
        self.indice_entry = QtGui.QLineEdit(self.groupBox)
        self.indice_entry.setObjectName(_fromUtf8("indice_entry"))
        self.gridLayout_2.addWidget(self.indice_entry, 14, 2, 1, 1)
        self.space_group_Box = QtGui.QComboBox(self.groupBox)
        self.space_group_Box.setObjectName(_fromUtf8("space_group_Box"))
        self.gridLayout_2.addWidget(self.space_group_Box, 15, 2, 1, 1)
        self.brightness_slider = QtGui.QSlider(self.groupBox)
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setObjectName(_fromUtf8("brightness_slider"))
        self.gridLayout_2.addWidget(self.brightness_slider, 16, 2, 1, 1)
        self.Calib_label = QtGui.QLabel(self.groupBox)
        self.Calib_label.setObjectName(_fromUtf8("Calib_label"))
        self.gridLayout_2.addWidget(self.Calib_label, 19, 0, 1, 1)
        self.Calib_box = QtGui.QComboBox(self.groupBox)
        self.Calib_box.setObjectName(_fromUtf8("Calib_box"))
        self.gridLayout_2.addWidget(self.Calib_box, 19, 2, 1, 1)
        self.Button_reset = QtGui.QPushButton(self.groupBox)
        self.Button_reset.setObjectName(_fromUtf8("Button_reset"))
        self.gridLayout_2.addWidget(self.Button_reset, 25, 0, 1, 6)
        self.reset_view_button = QtGui.QPushButton(self.groupBox)
        self.reset_view_button.setObjectName(_fromUtf8("reset_view_button"))
        self.gridLayout_2.addWidget(self.reset_view_button, 26, 0, 1, 6)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 5)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.mplvl = QtGui.QGridLayout()
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.gridLayout_7.addLayout(self.mplvl, 0, 1, 1, 1)
        Kikuchi.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Kikuchi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1213, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuStructure = QtGui.QMenu(self.menubar)
        self.menuStructure.setObjectName(_fromUtf8("menuStructure"))
        self.menuRefine = QtGui.QMenu(self.menubar)
        self.menuRefine.setObjectName(_fromUtf8("menuRefine"))
        Kikuchi.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Kikuchi)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Kikuchi.setStatusBar(self.statusbar)
        self.actionSave_figure = QtGui.QAction(Kikuchi)
        self.actionSave_figure.setObjectName(_fromUtf8("actionSave_figure"))
        self.actionCalculate_Schmid_factor = QtGui.QAction(Kikuchi)
        self.actionCalculate_Schmid_factor.setObjectName(_fromUtf8("actionCalculate_Schmid_factor"))
        self.actionCalculate_spectrum = QtGui.QAction(Kikuchi)
        self.actionCalculate_spectrum.setObjectName(_fromUtf8("actionCalculate_spectrum"))
        self.actionRefine_orientation = QtGui.QAction(Kikuchi)
        self.actionRefine_orientation.setObjectName(_fromUtf8("actionRefine_orientation"))
        self.menuSave.addAction(self.actionSave_figure)
        self.menuRefine.addAction(self.actionRefine_orientation)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuStructure.menuAction())
        self.menubar.addAction(self.menuRefine.menuAction())

        self.retranslateUi(Kikuchi)
        QtCore.QMetaObject.connectSlotsByName(Kikuchi)
        Kikuchi.setTabOrder(self.abc_entry, self.alphabetagamma_entry)
        Kikuchi.setTabOrder(self.alphabetagamma_entry, self.indice_entry)
        Kikuchi.setTabOrder(self.indice_entry, self.space_group_Box)
        Kikuchi.setTabOrder(self.space_group_Box, self.Calib_box)
        Kikuchi.setTabOrder(self.Calib_box, self.brightness_slider)
        Kikuchi.setTabOrder(self.brightness_slider, self.Button_reset)
        Kikuchi.setTabOrder(self.Button_reset, self.reset_view_button)

    def retranslateUi(self, Kikuchi):
        Kikuchi.setWindowTitle(_translate("Kikuchi", "Kikuchi", None))
        self.groupBox_9.setTitle(_translate("Kikuchi", "Bands", None))
        self.Button_addband.setText(_translate("Kikuchi", "Add bands", None))
        self.Button_run.setText(_translate("Kikuchi", "Run", None))
        self.Button_remove_band.setText(_translate("Kikuchi", "Remove band", None))
        self.plot_bands_button.setText(_translate("Kikuchi", "plot bands", None))
        self.Button_orientation.setText(_translate("Kikuchi", "Show bands", None))
        self.Button_add_center.setText(_translate("Kikuchi", "Add center", None))
        self.label.setText(_translate("Kikuchi", "tol. angle", None))
        self.groupBox.setTitle(_translate("Kikuchi", "Crystal Parameters", None))
        self.a_label.setText(_translate("Kikuchi", "a,b,c", None))
        self.alpha_label.setText(_translate("Kikuchi", "<html><head/><body><p>α,β,γ  </p></body></html>", None))
        self.indice_label.setText(_translate("Kikuchi", "Max Indices", None))
        self.space_group_label.setText(_translate("Kikuchi", "Space group", None))
        self.brightness_label.setText(_translate("Kikuchi", "Brightness", None))
        self.Calib_label.setText(_translate("Kikuchi", "Calibrations", None))
        self.Button_reset.setText(_translate("Kikuchi", "Reset points", None))
        self.reset_view_button.setText(_translate("Kikuchi", "Reset view", None))
        self.menuSave.setTitle(_translate("Kikuchi", "Open", None))
        self.menuStructure.setTitle(_translate("Kikuchi", "Structure", None))
        self.menuRefine.setTitle(_translate("Kikuchi", "Refine", None))
        self.actionSave_figure.setText(_translate("Kikuchi", "Open image", None))
        self.actionCalculate_Schmid_factor.setText(_translate("Kikuchi", "calculate Schmid factor", None))
        self.actionCalculate_spectrum.setText(_translate("Kikuchi", "Plot spectrum", None))
        self.actionRefine_orientation.setText(_translate("Kikuchi", "Refine orientation", None))

