# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaceUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName(_fromUtf8("Interface"))
        Interface.resize(1200, 755)
        self.centralwidget = QtGui.QWidget(Interface)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.mplvl = QtGui.QGridLayout()
        self.mplvl.setObjectName(_fromUtf8("mplvl"))
        self.gridLayout_7.addLayout(self.mplvl, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Button_reset = QtGui.QPushButton(self.groupBox)
        self.Button_reset.setObjectName(_fromUtf8("Button_reset"))
        self.gridLayout.addWidget(self.Button_reset, 37, 0, 1, 3)
        self.alphabetagamma_label = QtGui.QLabel(self.groupBox)
        self.alphabetagamma_label.setObjectName(_fromUtf8("alphabetagamma_label"))
        self.gridLayout.addWidget(self.alphabetagamma_label, 2, 0, 1, 1)
        self.abc_label = QtGui.QLabel(self.groupBox)
        self.abc_label.setObjectName(_fromUtf8("abc_label"))
        self.gridLayout.addWidget(self.abc_label, 0, 0, 1, 1)
        self.magnification_entry = QtGui.QLineEdit(self.groupBox)
        self.magnification_entry.setObjectName(_fromUtf8("magnification_entry"))
        self.gridLayout.addWidget(self.magnification_entry, 24, 2, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 26, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 8, 0, 1, 1)
        self.remove_condition_button = QtGui.QPushButton(self.groupBox)
        self.remove_condition_button.setObjectName(_fromUtf8("remove_condition_button"))
        self.gridLayout.addWidget(self.remove_condition_button, 27, 3, 1, 1)
        self.conditions_Listbox = QtGui.QListWidget(self.groupBox)
        self.conditions_Listbox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.conditions_Listbox.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.conditions_Listbox.setObjectName(_fromUtf8("conditions_Listbox"))
        self.gridLayout.addWidget(self.conditions_Listbox, 28, 0, 1, 5)
        self.z_label = QtGui.QLabel(self.groupBox)
        self.z_label.setObjectName(_fromUtf8("z_label"))
        self.gridLayout.addWidget(self.z_label, 23, 0, 1, 1)
        self.tilt_y_entry = QtGui.QLineEdit(self.groupBox)
        self.tilt_y_entry.setObjectName(_fromUtf8("tilt_y_entry"))
        self.gridLayout.addWidget(self.tilt_y_entry, 19, 2, 1, 2)
        self.add_condition_button = QtGui.QPushButton(self.groupBox)
        self.add_condition_button.setObjectName(_fromUtf8("add_condition_button"))
        self.gridLayout.addWidget(self.add_condition_button, 27, 0, 1, 3)
        self.tilt_z_entry = QtGui.QLineEdit(self.groupBox)
        self.tilt_z_entry.setObjectName(_fromUtf8("tilt_z_entry"))
        self.gridLayout.addWidget(self.tilt_z_entry, 23, 2, 1, 2)
        self.double_button = QtGui.QRadioButton(self.groupBox)
        self.double_button.setObjectName(_fromUtf8("double_button"))
        self.gridLayout.addWidget(self.double_button, 15, 3, 1, 1)
        self.image_angle_entry = QtGui.QLineEdit(self.groupBox)
        self.image_angle_entry.setObjectName(_fromUtf8("image_angle_entry"))
        self.gridLayout.addWidget(self.image_angle_entry, 12, 3, 1, 2)
        self.abc_entry = QtGui.QLineEdit(self.groupBox)
        self.abc_entry.setObjectName(_fromUtf8("abc_entry"))
        self.gridLayout.addWidget(self.abc_entry, 0, 2, 1, 3)
        self.euler_label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.euler_label.setFont(font)
        self.euler_label.setObjectName(_fromUtf8("euler_label"))
        self.gridLayout.addWidget(self.euler_label, 3, 0, 1, 1)
        self.image_angle_label = QtGui.QLabel(self.groupBox)
        self.image_angle_label.setObjectName(_fromUtf8("image_angle_label"))
        self.gridLayout.addWidget(self.image_angle_label, 12, 0, 1, 3)
        self.alphabetagamma_entry = QtGui.QLineEdit(self.groupBox)
        self.alphabetagamma_entry.setObjectName(_fromUtf8("alphabetagamma_entry"))
        self.gridLayout.addWidget(self.alphabetagamma_entry, 2, 2, 1, 3)
        self.micro_box = QtGui.QComboBox(self.groupBox)
        self.micro_box.setObjectName(_fromUtf8("micro_box"))
        self.gridLayout.addWidget(self.micro_box, 8, 2, 1, 3)
        self.pxtonm_label = QtGui.QLabel(self.groupBox)
        self.pxtonm_label.setObjectName(_fromUtf8("pxtonm_label"))
        self.gridLayout.addWidget(self.pxtonm_label, 24, 0, 1, 1)
        self.reset_view_button = QtGui.QPushButton(self.groupBox)
        self.reset_view_button.setObjectName(_fromUtf8("reset_view_button"))
        self.gridLayout.addWidget(self.reset_view_button, 37, 3, 1, 1)
        self.tilt_rot_button = QtGui.QRadioButton(self.groupBox)
        self.tilt_rot_button.setObjectName(_fromUtf8("tilt_rot_button"))
        self.gridLayout.addWidget(self.tilt_rot_button, 15, 4, 1, 1)
        self.beta_label_2 = QtGui.QLabel(self.groupBox)
        self.beta_label_2.setObjectName(_fromUtf8("beta_label_2"))
        self.gridLayout.addWidget(self.beta_label_2, 21, 0, 1, 1)
        self.crystal_checkBox = QtGui.QCheckBox(self.groupBox)
        self.crystal_checkBox.setObjectName(_fromUtf8("crystal_checkBox"))
        self.gridLayout.addWidget(self.crystal_checkBox, 7, 0, 1, 5)
        self.euler_entry = QtGui.QLineEdit(self.groupBox)
        self.euler_entry.setObjectName(_fromUtf8("euler_entry"))
        self.gridLayout.addWidget(self.euler_entry, 3, 2, 1, 3)
        self.normal_button = QtGui.QPushButton(self.groupBox)
        self.normal_button.setObjectName(_fromUtf8("normal_button"))
        self.gridLayout.addWidget(self.normal_button, 39, 0, 1, 5)
        self.euler_Listbox = QtGui.QListWidget(self.groupBox)
        self.euler_Listbox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.euler_Listbox.setObjectName(_fromUtf8("euler_Listbox"))
        self.gridLayout.addWidget(self.euler_Listbox, 40, 0, 1, 5)
        self.theta_signBox = QtGui.QCheckBox(self.groupBox)
        self.theta_signBox.setText(_fromUtf8(""))
        self.theta_signBox.setObjectName(_fromUtf8("theta_signBox"))
        self.gridLayout.addWidget(self.theta_signBox, 23, 4, 1, 1)
        self.single_button = QtGui.QRadioButton(self.groupBox)
        self.single_button.setObjectName(_fromUtf8("single_button"))
        self.gridLayout.addWidget(self.single_button, 15, 0, 1, 1)
        self.alpha_signBox = QtGui.QCheckBox(self.groupBox)
        self.alpha_signBox.setObjectName(_fromUtf8("alpha_signBox"))
        self.gridLayout.addWidget(self.alpha_signBox, 19, 4, 1, 1)
        self.beta_signBox = QtGui.QCheckBox(self.groupBox)
        self.beta_signBox.setText(_fromUtf8(""))
        self.beta_signBox.setObjectName(_fromUtf8("beta_signBox"))
        self.gridLayout.addWidget(self.beta_signBox, 21, 4, 1, 1)
        self.tilt_x_entry = QtGui.QLineEdit(self.groupBox)
        self.tilt_x_entry.setObjectName(_fromUtf8("tilt_x_entry"))
        self.gridLayout.addWidget(self.tilt_x_entry, 21, 2, 1, 2)
        self.alpha_label_2 = QtGui.QLabel(self.groupBox)
        self.alpha_label_2.setObjectName(_fromUtf8("alpha_label_2"))
        self.gridLayout.addWidget(self.alpha_label_2, 19, 0, 1, 1)
        self.direction_button = QtGui.QCheckBox(self.groupBox)
        self.direction_button.setObjectName(_fromUtf8("direction_button"))
        self.gridLayout.addWidget(self.direction_button, 26, 2, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox, 0, 1, 1, 1)
        Interface.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuStructure = QtGui.QMenu(self.menubar)
        self.menuStructure.setObjectName(_fromUtf8("menuStructure"))
        self.menuDraw = QtGui.QMenu(self.menubar)
        self.menuDraw.setObjectName(_fromUtf8("menuDraw"))
        Interface.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Interface)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Interface.setStatusBar(self.statusbar)
        self.actionSave_figure = QtGui.QAction(Interface)
        self.actionSave_figure.setObjectName(_fromUtf8("actionSave_figure"))
        self.actionCalculate_Schmid_factor = QtGui.QAction(Interface)
        self.actionCalculate_Schmid_factor.setObjectName(_fromUtf8("actionCalculate_Schmid_factor"))
        self.actionCalculate_spectrum = QtGui.QAction(Interface)
        self.actionCalculate_spectrum.setObjectName(_fromUtf8("actionCalculate_spectrum"))
        self.actionDirections_planes = QtGui.QAction(Interface)
        self.actionDirections_planes.setObjectName(_fromUtf8("actionDirections_planes"))
        self.menuSave.addAction(self.actionSave_figure)
        self.menuDraw.addAction(self.actionDirections_planes)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuStructure.menuAction())
        self.menubar.addAction(self.menuDraw.menuAction())

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)
        Interface.setTabOrder(self.abc_entry, self.alphabetagamma_entry)
        Interface.setTabOrder(self.alphabetagamma_entry, self.euler_entry)
        Interface.setTabOrder(self.euler_entry, self.crystal_checkBox)
        Interface.setTabOrder(self.crystal_checkBox, self.micro_box)
        Interface.setTabOrder(self.micro_box, self.image_angle_entry)
        Interface.setTabOrder(self.image_angle_entry, self.single_button)
        Interface.setTabOrder(self.single_button, self.double_button)
        Interface.setTabOrder(self.double_button, self.tilt_rot_button)
        Interface.setTabOrder(self.tilt_rot_button, self.tilt_y_entry)
        Interface.setTabOrder(self.tilt_y_entry, self.alpha_signBox)
        Interface.setTabOrder(self.alpha_signBox, self.tilt_x_entry)
        Interface.setTabOrder(self.tilt_x_entry, self.beta_signBox)
        Interface.setTabOrder(self.beta_signBox, self.tilt_z_entry)
        Interface.setTabOrder(self.tilt_z_entry, self.theta_signBox)
        Interface.setTabOrder(self.theta_signBox, self.magnification_entry)
        Interface.setTabOrder(self.magnification_entry, self.direction_button)
        Interface.setTabOrder(self.direction_button, self.add_condition_button)
        Interface.setTabOrder(self.add_condition_button, self.remove_condition_button)
        Interface.setTabOrder(self.remove_condition_button, self.conditions_Listbox)
        Interface.setTabOrder(self.conditions_Listbox, self.Button_reset)
        Interface.setTabOrder(self.Button_reset, self.reset_view_button)
        Interface.setTabOrder(self.reset_view_button, self.normal_button)
        Interface.setTabOrder(self.normal_button, self.euler_Listbox)

    def retranslateUi(self, Interface):
        Interface.setWindowTitle(_translate("Interface", "interface determination", None))
        self.Button_reset.setText(_translate("Interface", "Reset points", None))
        self.alphabetagamma_label.setText(_translate("Interface", "<html><head/><body><p>α, β, γ</p></body></html>", None))
        self.abc_label.setText(_translate("Interface", "a,b,c", None))
        self.label.setText(_translate("Interface", "<html><head/><body><p><span style=\" font-weight:600;\">Measure</span></p></body></html>", None))
        self.label_2.setText(_translate("Interface", "<html><head/><body><p><span style=\" font-weight:600;\">Microscope</span></p></body></html>", None))
        self.remove_condition_button.setText(_translate("Interface", "Remove", None))
        self.z_label.setText(_translate("Interface", "θ  (°)", None))
        self.add_condition_button.setText(_translate("Interface", "Add data", None))
        self.double_button.setText(_translate("Interface", "double (α,β)", None))
        self.euler_label.setText(_translate("Interface", "<html><head/><body><p><span style=\" font-weight:400;\">Euler angles</span></p></body></html>", None))
        self.image_angle_label.setText(_translate("Interface", "<html><head/><body><p>Image-α tilt angle</p></body></html>", None))
        self.pxtonm_label.setText(_translate("Interface", "Magnification", None))
        self.reset_view_button.setText(_translate("Interface", "Reset view", None))
        self.tilt_rot_button.setText(_translate("Interface", "tilt rot (α,θ)", None))
        self.beta_label_2.setText(_translate("Interface", "<html><head/><body><p>β (°)</p></body></html>", None))
        self.crystal_checkBox.setText(_translate("Interface", "Use lattice coordinates", None))
        self.normal_button.setText(_translate("Interface", "Get normal/direction", None))
        self.single_button.setText(_translate("Interface", "single (α)", None))
        self.alpha_signBox.setText(_translate("Interface", "AC", None))
        self.alpha_label_2.setText(_translate("Interface", "<html><head/><body><p>α (°)</p></body></html>", None))
        self.direction_button.setText(_translate("Interface", "direction", None))
        self.menuSave.setTitle(_translate("Interface", "Open", None))
        self.menuStructure.setTitle(_translate("Interface", "Structure", None))
        self.menuDraw.setTitle(_translate("Interface", "Draw", None))
        self.actionSave_figure.setText(_translate("Interface", "Open image", None))
        self.actionCalculate_Schmid_factor.setText(_translate("Interface", "calculate Schmid factor", None))
        self.actionCalculate_spectrum.setText(_translate("Interface", "Plot spectrum", None))
        self.actionDirections_planes.setText(_translate("Interface", "directions/planes", None))

